version: "3"

services:
  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - alocacao/aplicacao/redis_eventconsumer.py
        
  api:
    image: alocacao-imagem
    depends_on:
      - redis_pubsub
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - REDIS_HOST=redis
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=alocacao/aplicacao/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    # entrypoint:
    #   - gunicorn 
    #   - alocacao.aplicacao.flask_app:app
    #   - -b 0.0.0.0:80
    #   - -t 3600
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    stdin_open: true
    tty: true
    ports:
      - "5005:80"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=alocacao
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alocacao@admin.com
      PGADMIN_DEFAULT_PASSWORD: abc123
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - postgres
    ports:
      - "5050:5050"

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"
