"""produtos

Revision ID: 98d26f257516
Revises: 
Create Date: 2021-05-07 19:29:37.064793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d26f257516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linhas_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('_qtd_comprada', sa.Integer(), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['produtos.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alocacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['linhas_pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alocacoes')
    op.drop_table('lotes')
    op.drop_table('produtos')
    op.drop_table('linhas_pedido')
    # ### end Alembic commands ###
