"""alocacao_view

Revision ID: 6e8d48abafb8
Revises: 
Create Date: 2021-05-20 18:40:13.689892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8d48abafb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alocacoes_view',
    sa.Column('pedido_id', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('ref_lote', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alocacoes_view')
    # ### end Alembic commands ###
