@startuml

class AbstractRepository
{
    add(Produto)
    get() -> Produto
}

class TrackingRepository
{
    seen: set[Produto]
    __init__(AbstractRepository)
    add()
    get()
}

class Produto

class SQLAlchemyRepository
{
    session
    add(Produto)
    get() -> Produto
}

abstract UOW
{
    produtos: AbstractRepository
}

class SQLAlchemyUOW 
{

}

AbstractRepository .. Produto
TrackingRepository .. Produto
SQLAlchemyRepository o-- Produto
TrackingRepository o-- AbstractRepository
UOW <|-- SQLAlchemyUOW
SQLAlchemyUOW o-- SQLAlchemyRepository
SQLAlchemyUOW o-- TrackingRepository
UOW o-- AbstractRepository

@enduml